### PR TITLE
Update pt-PT locale

### PR DESCRIPTION
**Pull request by hugok79**
Update Portuguese (Portugal) Translation

### CODE REVIEW

**Comment by Maria-Sukhova** [comment]
Hi!
Thank you for your translation! I would like to check: is the translation for licGetLicense: 'Get license now' - 'Obter a licença' correct? not 'Obter a license agora?

**Comment by hugok79** [comment]
> Hi! Thank you for your translation! I would like to check: is the translation for licGetLicense: 'Get license now' - 'Obter a licença' correct? not 'Obter a license agora?

@Maria-Sukhova I changed it so that the translation would be more simple/straightforward...
Practically speaking **Get license now** in Portuguese is **Obter a licença agora** but **Obter a licença** means the same.

**Comment by Maria-Sukhova** [comment]
> > Hi! Thank you for your translation! I would like to check: is the translation for licGetLicense: 'Get license now' - 'Obter a licença' correct? not 'Obter a license agora?
> 
> @Maria-Sukhova I changed it so that the translation would be more simple/short/straightforward... Practically speaking **Get license now** in Portuguese is **Obter a licença agora** but **Obter a licença** means the same.

I see, thank you!

**Review by Maria-Sukhova — APPROVED** [review]

**Comment by hugok79** [comment]
@Maria-Sukhova  @maxkadushkin Thank you!

**Comment by hugok79** [comment]
I have also been translating onlyoffice on the TemLab translatio system platform into Portuguese (Portugal). I will try to keep the translation updated here also 👍

**Pull request merged**
