### PR TITLE
Improvement of Spanish translation

### PR DESCRIPTION
**Pull request by Julvenzor**
Hi!

I am a Spanish writer and linguist. Your program is getting better and better, but a large part of the Spanish translation is full of literal translations, an unnatural use of language and a lack of idiomaticity.

I have corrected what I have seen in the context of the program. In the next few days I will review the strings corresponding to the webapps.

Regards.

### CODE REVIEW

**Review by Maria-Sukhova — COMMENTED** [review]
Hi!
Thank you for your translations!
I would like to make two clarifications: here,
lines 66-67: Document = Opening...
lines 559-560: Sign Up = Create portal
Please, check these translations and we'll update the files.
Best regards,

**Comment by Julvenzor** [comment]
> Hi! Thank you for your translations! I would like to make two clarifications: here, lines 66-67: Document = Opening... lines 559-560: Sign Up = Create portal Please, check these translations and we'll update the files. Best regards,

Hello. I'm willing to make any changes, but I would like to clarify why "Document" means "Opening..." or "Sign Up" means "Create Portal".

"Document" is translated as "Documento"; "Opening document...", in the context of an already selected document, it would be "Abriendo documento...". However, we can also leave it at "abriendo..." if we assume that we are referring to the document. This is OK.

"Sign up", on all websites, is translated as the action of creating an account: "crear cuenta" or "registrarse". "Create portal" would be translated literally as "Crear portal", but "portal" doesn't mean "account" in Spanish. "Crear un portal" would mean "create a gateway" or "create a web". "Crear oficina en la nube", the previous translation, is understandable, but it sounds unnatural. It's not something a native speaker would say. In English there are certain nuances, such as "create a cloud office" (= create an office on the cloud), which a Spanish speaker would simplify into "crear cuenta en la nube" or just "crear cuenta".

Regards.

**Review by Maria-Sukhova — COMMENTED** [review]
Hello!
Thank you for the clarifications. For this document, please refer to the file "en.ts", for example, https://github.com/ONLYOFFICE/desktop-apps/blob/develop/win-linux/langs/en.ts. We can see that as a rule, <source> is the name of the key and the text of the message at the same time. However, sometimes the message is changed. So, it appears in <translation> while the name of the key is left unchanged. A user sees the <translation> text.
So, I suggest the following options:
"Abriendo..."
"Crear cuenta en la nube".
Best regards,

**Comment by Julvenzor** [comment]
I understand. Everything should be OK now.

Regards.

**Pull request merged**
